### ISSUE TITLE
Cache not working

### ISSUE THREAD

**Issue by shivsah** [obendidi/httpx-cache#88] opened 2023-09-13 21:20 UTC
`
PROC_SHOPIFY_CACHE = 12 * 60 * 60
async def proc_shopify(order_no):
    url = f"https://alfuuktopkh.myshopify.com/admin/api/2023-07/orders.json?name={order_no}&status=any"
    headers = {
        'Content-Type': 'application/json',
        'X-Shopify-Access-Token': ADMIN_token,
        "cache-control": f"max-age={PROC_SHOPIFY_CACHE}"
    }
    async with httpx_cache.AsyncClient() as client:
        response = await client.get(url, headers=headers)`

I don't think caching is working on the request, as the response is similar in multiple runs.

**Comment by obendidi** [comment] 2023-09-13 22:58
> I don't think caching is working on the request, as the response is similar in multiple runs.

Can you give more details about the issue ?

If my understanding is correct, you mean multiple runs of your app/script, and not multiple runs of the request in the same program. I see you are using the default memory cache in your `httpx_cache.AsyncClient`, so maybe just switching that to a `FileCache` or a `RedisCache` wuld solve your issue.

More in cache type and how to use them: https://obendidi.github.io/httpx-cache/guide/#cache-types

The (default) in-memory dict cache is cleared at the end of your script (it's a simple python dict), so you can't reuse cache across multiple runs of your script. 
The file/redis cache are more consistent.

**Comment by shivsah** [comment] 2023-09-14 18:42
I'm using fastapi and Uvicorn, so the the request is basically to our other servers, so it's not a complete re-run, i'll still consider running redis or something though

**Comment by shivsah** [comment] 2023-09-15 07:20
Does httpx_cache support caching of POST requests as well, or do we have to use custom transport

**Comment by obendidi** [comment] 2023-09-15 12:28
>I'm using fastapi and Uvicorn, so the the request is basically to our other servers, so it's not a complete re-run, i'll still consider running redis or something though

If you are using `httpx_cache` in fastapi endpoints, you can keep a single cache lient in the app state so that it shared by all endpoints and request instances, creating a different `httpx_cache.Client` for each request, will discard the cache at the end of that request, example:

```py
from fastapi import FastAPI, Depends, Request
import httpx_cache


async def lifespan(app: FastAPI):
    print("startup ...")
    httpx_client = httpx_cache.AsyncClient()
    app.state.client = httpx_client
    yield
    print("shutdown ...")
    await httpx_client.aclose()


app = FastAPI(lifespan=lifespan)


async def get_httpx_client(request: Request) -> httpx_cache.AsyncClient:
    return request.app.state.httpx_client


@app.get("/")
async def get_httpbin(
    httpx_client: httpx_cache.AsyncClient = Depends(get_httpx_client),
):
    response = await httpx_client.get("https://httpbin.org/get")
    response.raise_for_status()
    return response.json()
```

>  Does httpx_cache support caching of POST requests as well, or do we have to use custom transport
Not by default, but you can easily add it if you want, links in the docs:
* https://obendidi.github.io/httpx-cache/cache_control/
* https://obendidi.github.io/httpx-cache/api/#client

```py
httpx_cache.Client(cacheable_methods=["GET", "POST"])
```

You should keep in mind that you probably don't want to cache `POST` request, because they are requests that make changes in the requested server, so it doesn't make sens to cache them (it might be different for your use case, so you know better :) )

**Comment by shivsah** [comment] 2023-09-15 13:49
So yeah, i was having some issues with the remote redis-server hosted by redis, so i move to file cache, which is working great..

Actually i'm trying to cache the response of the POST, as it's for checking the status of an order, and post value has a 2step key in the body. 

But i'm thinking of a different approach now, i'll instead host that particular script seprately, and have a get request to get data from that script, that way, i have more control over caching.

**Comment by obendidi** [comment] 2023-09-17 09:20
Closing as the issue is no longer related to httpx-cache

**Closed** 2023-09-17 09:21 UTC
